### PR TITLE
Open dev-master 2.0.x

### PR DESCRIPTION
**Pull request by vody105**

### CODE REVIEW

**Comment by vody105** [comment]
@f3l1x

**Comment by jiripudil** [comment]
As this package is nowhere near 3.0, it seems a bit too far off. I'd like to see some reasoning behind this first, starting with a couple of questions:

What's the best practice on this? What are people accustomed to? Why `3.0-dev` and not `2.1-dev`? Or even `2.0-dev` as the docs [seem to imply](https://getcomposer.org/doc/articles/aliases.md#branch-alias)? [Apparently](https://github.com/nette/application/commit/60b9c8a3f165bbb5e0c1ac88cef582516f95d088) Nette uses it that way too 🤔

**Comment by f3l1x** [comment]
You're right that it should be 2.1-dev. Main purpose of this is to allow end users test dev-master but only until next release is released. I am doing it for all packages, it's much easier to test them in our applications before real version is tagged.

Can we change it to 2.1-dev?

**Comment by jiripudil** [comment]
I really wouldn't even stand against `2.0.x-dev`. It feels confusing to tell people to install `^2.1@dev` to try out bugfixes which then get released as `2.0.1`

**Comment by f3l1x** [comment]
Sure, why not. :-) @vody105 could you please change it as @jiripudil said?

**Comment by vody105** [comment]
Sure. Imho `2.1-dev` is perfectly fine because it does not contain only bugfixes but 2.0.x-dev is also 👍 so `2.0.x` it is 🙂

**Comment by jiripudil** [comment]
> it does not contain only bugfixes

Well, currently it does not contain anything on top of the latest stable 😉 I guess that's why `2.0-dev` feels more natural to me – nobody knows yet if the next release is going to be 2.0.1 or 2.1.0 or even 3.0.0, so the current range (`2.0.x`) is the only thing that's certain at this point.

**Comment by vody105** [comment]
@f3l1x ping

**Pull request merged**
