### PR TITLE
moved executing scripts from composer to makefile

### PR DESCRIPTION
**Pull request by petrparolek**

### CODE REVIEW

**Comment by f3l1x** [comment]
It's contributte standard. :-) What do you think @jiripudil ?

**Comment by jiripudil** [comment]
but but

Well, yeah, I understand it's for the sake of consistency with the Contributte ecosystem, so I'm not gonna dispute this, but for the record, I fail to see the benefits :)

**Comment by f3l1x** [comment]
Thank you. First what came to my mind is this.

https://github.com/contributte/redis/blob/7fa4d682a0e113ce6be69e8cab69b4c09e83304d/Makefile#L8-L13

In Github Actions use different codesniffer formatter.

In makefile you have much more power. :-)

**Comment by jiripudil** [comment]
Well, if the goal is to provide a consistent experience for developers so that they can contribute to any Contributte packages without having to think how to run stuff in each one, then Github Actions could easily run a different script. It wouldn’t make any practical difference to contributors because they would still only run the original one locally. I'd say both `ifdef GITHUB_ACTION` and `"cs-github-actions": "use --different --options"` even communicate the intent equally clearly.

I can see how Makefile can be useful if you have multiple build systems in a project, or if you need to rebuild artifacts based on other files changing, but neither is the case in most Contributte packages, in fact, the only difference to Composer scripts that I can see here is that it forces you to install additional software (Make) and additional IntelliJ plugin.

But then again, this has been already decided long ago and there's nothing I can do about it, so there's no point in me going against the flow. I'm just biased because I use Composer scripts extensively, which I cannot say about Makefile, and it's hard for me to part with the ways I'm used to do things :)

**Comment by f3l1x** [comment]
Understand. I suggest discuss it in person on some PoSobota or other event. We can figure it out.

**Pull request merged**
